#!/usr/bin/env bash
# Full local verification of XatBox mobile + backend (Linux/macOS host, no device).
#
#   scripts/verify.sh                 # pub get, analyze, unit/widget tests, e2e (host), Go vet + unit tests
#   scripts/verify.sh --with-docker   # + Go integration suites (testcontainers, needs Docker)
#
# Environment overrides:
#   FLUTTER_BIN_DIR  (default ~/.local/flutter/bin)   GO_BIN_DIR (default ~/.local/go/bin)
#   GOMODCACHE       (default $HOME/go/pkg/mod; point it at a warm cache to work offline)
#
# E2E host mode: `flutter test` treats every path under integration_test/ as a
# device run, so the flows are imported by a generated runner in build/e2e_host/
# and executed with the ordinary widget-test binding (fake time, no device).
# On an Android emulator the same files run via scripts/e2e-android.ps1.
set -euo pipefail

WITH_DOCKER=0
for arg in "$@"; do
  case "$arg" in
    --with-docker) WITH_DOCKER=1 ;;
    -h|--help) sed -n '2,15p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg (see --help)" >&2; exit 2 ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export PATH="${FLUTTER_BIN_DIR:-$HOME/.local/flutter/bin}:${GO_BIN_DIR:-$HOME/.local/go/bin}:$PATH"
export GOMODCACHE="${GOMODCACHE:-$HOME/go/pkg/mod}"
export GOFLAGS="${GOFLAGS:-}"

declare -a RESULTS=()
FAILED=0

# step <name> <command...>: runs the command, records PASS/FAIL, never aborts the script.
step() {
  local name="$1"; shift
  local started=$SECONDS
  echo
  echo "==> $name"
  local rc=0
  "$@" || rc=$?
  local took=$((SECONDS - started))
  if [[ $rc -eq 0 ]]; then
    RESULTS+=("PASS  ${name} (${took}s)")
  else
    RESULTS+=("FAIL  ${name} (exit ${rc}, ${took}s)")
    FAILED=1
  fi
}

skip() { RESULTS+=("SKIP  $1: $2"); }

have() { command -v "$1" >/dev/null 2>&1; }

pub_get() { flutter pub get --offline || flutter pub get; }

# Generates build/e2e_host/all_flows_test.dart importing every integration_test/*_test.dart.
e2e_host() {
  local dir="$ROOT/build/e2e_host" runner
  runner="$dir/all_flows_test.dart"
  mkdir -p "$dir"
  shopt -s nullglob
  local files=("$ROOT"/integration_test/*_test.dart)
  shopt -u nullglob
  if [[ ${#files[@]} -eq 0 ]]; then
    echo "no integration_test/*_test.dart files" >&2
    return 1
  fi
  {
    echo "// GENERATED by scripts/verify.sh: host-mode runner for integration_test/. Do not edit."
    for f in "${files[@]}"; do
      local n; n="$(basename "$f" .dart)"
      echo "import '../../integration_test/$n.dart' as $n;"
    done
    echo
    echo "void main() {"
    for f in "${files[@]}"; do
      echo "  $(basename "$f" .dart).main();"
    done
    echo "}"
  } >"$runner"
  flutter test --no-pub "$runner"
}

go_module() {
  local mod="$1"
  (cd "$ROOT/backend/$mod" && go vet ./... && go test -short -count=1 ./...)
}

go_integration() {
  local mod="$1"
  local cmd="cd '$ROOT/backend/$mod' && PATH='$PATH' GOMODCACHE='$GOMODCACHE' TESTCONTAINERS_RYUK_DISABLED=true go test ./test/integration/ -count=1 -timeout 30m"
  if docker info >/dev/null 2>&1; then
    bash -c "$cmd"
  elif have sg && sg docker -c "docker info" >/dev/null 2>&1; then
    sg docker -c "$cmd"
  else
    echo "Docker is not reachable (tried docker and sg docker)" >&2
    return 1
  fi
}

# ---- Flutter ------------------------------------------------------------------
if have flutter; then
  step "flutter pub get" pub_get
  step "flutter analyze" flutter analyze --no-pub
  step "flutter test (unit + widget, test/)" flutter test --no-pub
  step "e2e flows, host mode (integration_test/)" e2e_host
else
  skip "flutter" "flutter not found (set FLUTTER_BIN_DIR)"
  FAILED=1
fi

# ---- Go -------------------------------------------------------------------------
if have go; then
  for mod in platform chat-service call-service; do
    step "go vet + go test -short: backend/$mod" go_module "$mod"
  done
  if [[ $WITH_DOCKER -eq 1 ]]; then
    for mod in chat-service call-service; do
      step "go integration (Docker): backend/$mod" go_integration "$mod"
    done
  else
    skip "go integration" "pass --with-docker to run backend/*/test/integration"
  fi
else
  skip "go" "go not found (set GO_BIN_DIR)"
  FAILED=1
fi

echo
echo "================ verify summary ================"
printf '%s\n' "${RESULTS[@]}"
echo "================================================"
if [[ $FAILED -ne 0 ]]; then
  echo "RESULT: FAIL"
  exit 1
fi
echo "RESULT: PASS"
